added character mapping functionality

diff --git a/tests/testsuite b/tests/testsuite
--- a/tests/testsuite
+++ b/tests/testsuite
@@ -303,15 +303,16 @@ at_times_file=$at_suite_dir/at-times
 # List of the tested programs.
 at_tested='mksfxa mklcpa sfxa'
 # List of the all the test groups.
-at_groups_all=' banner-1 1 banner-2 2 banner-3 3'
+at_groups_all=' banner-1 1 2 banner-2 3 banner-3 4'
 # As many dots as there are digits in the last test group number.
 # Used to normalize the test group numbers so that `ls' lists them in
 # numerical order.
 at_format='.'
 # Description of all the test groups.
 at_help_all='1;mksfxa.at:23;The file not existing.;non-existent-file;
-2;mklcpa.at:23;The file not existing.;non-existent-file;
-3;sfxa.at:23;The file not existing.;non-existent-file;
+2;mksfxa.at:29;The file of length zero.;zero-length-file;
+3;mklcpa.at:23;The file not existing.;non-existent-file;
+4;sfxa.at:23;The file not existing.;non-existent-file;
 '
 
 at_keywords=
@@ -338,7 +339,7 @@ do
 	;;
 
     --version | -V )
-	echo "$as_me (SfxaTools 0.0.3)"
+	echo "$as_me (SfxaTools 0.0.4)"
 	exit 0
 	;;
 
@@ -494,7 +495,7 @@ fi
 # List of tests.
 if $at_list_p; then
   cat <<_ATEOF
-SfxaTools 0.0.3 test suite test groups:
+SfxaTools 0.0.4 test suite test groups:
 
  NUM: FILENAME:LINE      TEST-GROUP-NAME
       KEYWORDS
@@ -576,13 +577,13 @@ exec 5>$at_suite_log
 # Banners and logs.
 cat <<\_ASBOX
 ## --------------------------- ##
-## SfxaTools 0.0.3 test suite. ##
+## SfxaTools 0.0.4 test suite. ##
 ## --------------------------- ##
 _ASBOX
 {
   cat <<\_ASBOX
 ## --------------------------- ##
-## SfxaTools 0.0.3 test suite. ##
+## SfxaTools 0.0.4 test suite. ##
 ## --------------------------- ##
 _ASBOX
   echo
@@ -830,7 +831,53 @@ echo stdout:; cat $at_stdout
 case $at_status in
    77) echo 77 > $at_status_file
             exit 77;;
-   *);;
+   1) ;;
+   *) echo "mksfxa.at:26: exit code was $at_status, expected 1"
+      at_failed=:;;
+esac
+if $at_failed; then
+
+  echo 1 > $at_status_file
+  exit 1
+fi
+
+$at_traceon
+
+      $at_traceoff
+      $at_times_p && times >$at_times_file
+    ) 5>&1 2>&1 | eval $at_tee_pipe
+    at_status=`cat $at_status_file`
+    ;;
+
+  2 ) # 2. mksfxa.at:29: The file of length zero.
+    at_setup_line='mksfxa.at:29'
+    at_desc='The file of length zero.'
+    $at_quiet $ECHO_N "  2: The file of length zero.                     $ECHO_C"
+    at_xfail=no
+    (
+      echo "2. mksfxa.at:29: testing ..."
+      $at_traceon
+
+
+cat >zero <<'_ATEOF'
+_ATEOF
+
+$at_traceoff
+echo "mksfxa.at:32: mksfxa zero"
+echo mksfxa.at:32 >$at_check_line_file
+( $at_traceon; mksfxa zero ) >$at_stdout 2>$at_stder1
+at_status=$?
+grep '^ *+' $at_stder1 >&2
+grep -v '^ *+' $at_stder1 >$at_stderr
+at_failed=false
+echo stderr:; cat $at_stderr
+echo stdout:; cat $at_stdout
+case $at_status in
+   77) echo 77 > $at_status_file
+            exit 77;;
+   1) ;;
+   *) echo "mksfxa.at:32: exit code was $at_status, expected 1"
+      at_failed=:;;
 esac
 if $at_failed; then
 
@@ -855,13 +902,13 @@ Tests for mklcpa.
 _ATEOF
     ;;
 
-  2 ) # 2. mklcpa.at:23: The file not existing.
+  3 ) # 3. mklcpa.at:23: The file not existing.
     at_setup_line='mklcpa.at:23'
     at_desc='The file not existing.'
-    $at_quiet $ECHO_N "  2: The file not existing.                       $ECHO_C"
+    $at_quiet $ECHO_N "  3: The file not existing.                       $ECHO_C"
     at_xfail=no
     (
-      echo "2. mklcpa.at:23: testing ..."
+      echo "3. mklcpa.at:23: testing ..."
       $at_traceon
 
 
@@ -901,7 +948,9 @@ echo stdout:; cat $at_stdout
 case $at_status in
    77) echo 77 > $at_status_file
             exit 77;;
-   *);;
+   1) ;;
+   *) echo "mklcpa.at:26: exit code was $at_status, expected 1"
+      at_failed=:;;
 esac
 if $at_failed; then
 
@@ -926,13 +975,13 @@ Tests for sfxa.
 _ATEOF
     ;;
 
-  3 ) # 3. sfxa.at:23: The file not existing.
+  4 ) # 4. sfxa.at:23: The file not existing.
     at_setup_line='sfxa.at:23'
     at_desc='The file not existing.'
-    $at_quiet $ECHO_N "  3: The file not existing.                       $ECHO_C"
+    $at_quiet $ECHO_N "  4: The file not existing.                       $ECHO_C"
     at_xfail=no
     (
-      echo "3. sfxa.at:23: testing ..."
+      echo "4. sfxa.at:23: testing ..."
       $at_traceon
 
 
@@ -1256,7 +1305,7 @@ _ASBOX
   echo "Please send \`$as_me.log' and all information you think might help:"
   echo
   echo "   To: <aki@gsc.riken.jp>"
-  echo "   Subject: [SfxaTools 0.0.3] $as_me:$at_fail_list${at_fail_list:+ failed${at_xpass_list:+,}}$at_xpass_list${at_xpass_list:+ passed unexpectedly}"
+  echo "   Subject: [SfxaTools 0.0.4] $as_me:$at_fail_list${at_fail_list:+ failed${at_xpass_list:+,}}$at_xpass_list${at_xpass_list:+ passed unexpectedly}"
   echo
   if test $at_debug_p = false; then
     echo
